# Generated by Django 4.2.9 on 2024-02-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tester", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="kakao_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
